# -*- mode:python -*-

# Copyright (c) 2023 Starfive Private Ltd
# All rights reserved.
#

Import('*')

if env['CONF']['PROTOCOL'] == 'None':
    Return()

SimObject('D2DBridge.py', sim_objects=['D2DBridge'])

Source('D2DBridge.cc')
Source('D2DMsg.cc')